package com.skillstorms.backend.controller;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.skillstorms.backend.model.Hotel;
import com.skillstorms.backend.repository.HotelRepository;

@Controller // This means that this class is a Controller
@CrossOrigin(origins = "*")
@RequestMapping(path="/hotel") // This means URL's start with /demo (after Application path)
public class HotelController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private HotelRepository hotelRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public Hotel create(@Valid @RequestBody Hotel hotel) {
	hotelRepository.save(hotel);
    return hotel;
  }
  @GetMapping(path="/hello")
  public @ResponseBody String Hello() {
    // This returns a JSON or XML with the users
    return "Helo";
  }
  @GetMapping(path="/all")
  public @ResponseBody Iterable<Hotel> getAllCustomers() {
    // This returns a JSON or XML with the users
    return hotelRepository.findAll();
  }
}